# Site wide configuration

title: "Yibo's Blog"
description: "Everything that happens is perfectly destined"
logo: rubik_cube.jpg # 120x120 px default image used for Twitter summary card
teaser: /teaser/default.jpg # 400x250 px default teaser image used in image archive grid
locale:
url:
check_box: '<i class="fa fa-check-square-o">'
blank_box: '<i class="fa fa-square-o">'

default:
    -
        scope:
            type: "article"
        values:
            ads: false
            toc: false


# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
kramdown:
    input: GFM
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Zhangze
  email: zhangze1029@gmail.com
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: rubik_cube.jpg # 160x160 px image for author byline
disqus-shortname: yibo

future: true

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
